@echo off
echo ========================================
echo   WOODSOFT EXTEND - BUILD TOOL
echo ========================================
echo.

REM Check if Python is available
python --version >nul 2>&1
if errorlevel 1 (
    echo ERROR: Python not found!
    echo Please install Python 3.8+ from python.org
    echo.
    pause
    exit /b 1
)

echo Python detected:
python --version
echo.

REM Step 1: Clean old build files
echo [1/4] Cleaning old build files...
if exist build (
    rmdir /s /q build
    echo   - Removed build/
)
if exist dist (
    rmdir /s /q dist
    echo   - Removed dist/
)
if exist "*.spec~" (
    del /q "*.spec~"
    echo   - Removed backup spec files
)
echo   Clean completed
echo.

REM Step 2: Check dependencies
echo [2/4] Checking dependencies...
python -c "import ttkbootstrap" 2>nul
if errorlevel 1 (
    echo   ttkbootstrap not found
    goto :missing_deps
)
python -c "import PIL" 2>nul
if errorlevel 1 (
    echo   PIL/Pillow not found
    goto :missing_deps
)
python -c "import keyring" 2>nul
if errorlevel 1 (
    echo   keyring not found
    goto :missing_deps
)
python -c "import requests" 2>nul
if errorlevel 1 (
    echo   requests not found
    goto :missing_deps
)
python -c "import webview" 2>nul
if errorlevel 1 (
    echo   pywebview not found
    goto :missing_deps
)
python -c "import PyInstaller" 2>nul
if errorlevel 1 (
    echo   PyInstaller not found
    goto :missing_deps
)

echo   All dependencies OK
echo.

REM Step 3: Check critical files
echo [3/4] Checking critical files...
if not exist "app.py" (
    echo   app.py not found!
    goto :error_exit
)
echo   app.py OK
if not exist "app.spec" (
    echo   app.spec not found!
    goto :error_exit
)
echo   app.spec OK
if not exist "light.ico" (
    echo   WARNING: light.ico not found - window icon will be missing
) else (
    echo   light.ico OK
)
if not exist "i18n" (
    echo   i18n folder not found!
    goto :error_exit
)
echo   i18n folder OK
echo.

REM Step 3b: Generate version file with today's date
echo [3b/4] Generating version file...
python -c "import datetime; v='Ver. '+datetime.date.today().strftime('%%d.%%m.%%Y'); open('version.py','w',encoding='utf-8').write('# Auto-generated by build.bat\nAPP_VERSION=\"'+v+'\"\n'); print('  Version: '+v)"
if errorlevel 1 (
    echo   WARNING: Failed to generate version.py
)
echo.

REM Step 4: Build executable
echo [4/4] Building executable with PyInstaller...
echo   This may take 1-3 minutes...
echo.
python -m PyInstaller --clean app.spec
if errorlevel 1 (
    echo.
    echo   Build FAILED!
    echo   Check errors above and fix them.
    echo.
    goto :error_exit
)
echo.
echo   Build completed
echo.

REM Check output
if not exist "dist\Woodsoft_Extend.exe" (
    echo   EXE file not found in dist\
    goto :error_exit
)
echo   EXE file created

REM Display file size
for %%I in ("dist\Woodsoft_Extend.exe") do (
    set size=%%~zI
)
set /a size_mb=%size% / 1048576
echo   File size: %size_mb% MB
echo.

REM Completed
echo ========================================
echo        BUILD SUCCESSFUL!
echo ========================================
echo.
echo Output location:
echo   dist\Woodsoft_Extend.exe
echo.
echo Next steps:
echo   1. Run the EXE to test
echo   2. Verify that:
echo      - Login and License checks work
echo      - Mode 1 runs maximized in WebView2
echo      - Language switching works
echo.
pause
exit /b 0

:missing_deps
echo.
echo Missing dependencies detected!
echo.
echo Please install all required packages:
echo   pip install -r requirements.txt
echo.
pause
exit /b 1

:error_exit
echo.
echo BUILD FAILED!
echo.
pause
exit /b 1
